[package]
name = "connexa-signaling"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
connexa-core.workspace = true
connexa-protocol.workspace = true
connexa-security.workspace = true
dashmap.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
